### ISSUE TITLE
Incompatible with eslint-plugin-vue v10.7.0+ - Cannot find module 'eslint-plugin-vue/lib/utils'

### ISSUE THREAD

**Issue by lehni** [rashfael/eslint-plugin-vue-pug#35]
## Description

  eslint-plugin-vue-pug is incompatible with eslint-plugin-vue v10.7.0 and later due to a breaking change in the directory
  structure. In eslint-plugin-vue v10.7.0, the internal structure changed from `lib/` to `dist/`, breaking all imports that
  reference the old paths.

  ## Version Compatibility

  - ✅ Works with eslint-plugin-vue v10.6.2 and earlier
  - ❌ Breaks with eslint-plugin-vue v10.7.0 and later

  ## Error

  Error: Cannot find module 'eslint-plugin-vue/lib/utils'
  Require stack:
  - /node_modules/eslint-plugin-vue-pug/lib/rules/component-name-in-template-casing.js
  - /node_modules/eslint-plugin-vue-pug/lib/index.js

  ## Affected Files

  The following files import from the old `lib/` path structure:

  1. `lib/rules/component-name-in-template-casing.js`:
     - `require('eslint-plugin-vue/lib/utils')`
     - `require('eslint-plugin-vue/lib/utils/casing')`
     - `require('eslint-plugin-vue/lib/utils/regexp')`

  2. `lib/rules/no-pug-control-flow.js`:
     - `require('eslint-plugin-vue/lib/utils')`

  ## Environment

  - eslint-plugin-vue-pug: v1.0.0-alpha.4
  - eslint-plugin-vue: v10.7.0 (breaks) vs v10.6.2 (works)
  - Node.js: v24.10.0

  ## Suggested Fix

  Update all imports from:
  - `eslint-plugin-vue/lib/utils` → `eslint-plugin-vue/dist/utils`
  - `eslint-plugin-vue/lib/utils/casing` → `eslint-plugin-vue/dist/utils/casing`
  - `eslint-plugin-vue/lib/utils/regexp` → `eslint-plugin-vue/dist/utils/regexp`

  Alternatively, update the `peerDependencies` in package.json to restrict to `eslint-plugin-vue: "^10.0.0 <10.7.0"` until the
   imports can be updated.

  ## Workaround

  Pin eslint-plugin-vue to v10.6.2 until this is resolved.

**Comment by markusheiden** [comment]
I added the PR https://github.com/rashfael/eslint-plugin-vue-pug/pull/36 for this.

**Comment by rashfael** [comment]
Fix has been released!

**Comment by lehni** [comment]
Much appreciated @markusheiden and @rashfael!
